version: '3.2'
services:
  service:
    image: "openiamdocker/redis:alpine-${OPENIAM_VERSION_NUMBER}-${BUILD_ENVIRONMENT}"
    environment:
      REDIS_PASSWORD: "${REDIS_PASSWORD}"
      OPENIAM_LOG_LEVEL: trace
    deploy:
      placement:
        constraints:
        - node.role == ${NODE_ROLE:-worker}
      mode: replicated
      replicas: 1
      resources:
        limits:
          memory: 512m
      restart_policy:
        condition: on-failure
      update_config:
        delay: 1s
        parallelism: 2
    networks:
      openiam_private:
        aliases:
          - redis
    ports:
      - "6379:6379"
    stop_grace_period: 30s
    healthcheck:
      test: "(healthcheck.sh 120 && exit 0) || exit 1"
      interval: 30s
      timeout: 120s
      retries: 5

networks:
  openiam_private:
    external:
      name: openiam_private