version: '2.1'
services:
  service:
    image: "openiamdocker/redis:alpine-${OPENIAM_VERSION_NUMBER}-${BUILD_ENVIRONMENT}"
    environment:
      REDIS_PASSWORD: "${REDIS_PASSWORD}"
      OPENIAM_LOG_LEVEL: trace
    mem_limit: 512m
    networks:
      openiam:
        aliases:
          - redis
    ports:
      - "6379:6379"
    stop_grace_period: 30s
    healthcheck:
      test: "(healthcheck.sh 120 && exit 0) || exit 1"
      interval: 30s
      timeout: 120s
      retries: 5

networks:
  openiam:
    external:
      name: openiam