---
version: 2

jobs:
  build:
    machine: true
    enviornment:
      TZ: "/usr/share/zoneinfo/Etc/UTC"
      DEBIAN_FRONTEND: "noninteractive"
      TERM: dumb
    steps:
      - checkout
      - run:
          name: Build 2.1 images
          command: |
             /bin/sh ci/setup.sh
             /bin/sh back-end/2.1/mysql/ci/build.sh
  build_one_tier_v2_1:
    machine: true
    enviornment:
      TZ: "/usr/share/zoneinfo/Etc/UTC"
      DEBIAN_FRONTEND: "noninteractive"
      TERM: dumb
    steps:
      - checkout
      - run:
          name: Build 2.1 images
          command: |
             /bin/sh ci/setup.sh
             /bin/sh one-tier/2.1/mysql/ci/build.sh
  build_ui_v2_1:
    machine: true
    enviornment:
      TZ: "/usr/share/zoneinfo/Etc/UTC"
      DEBIAN_FRONTEND: "noninteractive"
      TERM: dumb
    steps:
      - checkout
      - run:
          name: Build 2.1 images
          command: |
             /bin/sh ci/setup.sh
             /bin/sh ui/2.1/ci/build.sh
             
             
workflows:
  version: 2
  build_local:
    jobs:
      - build
      - build_one_tier_v2_1
      - build_ui_v2_1