---
version: 2

jobs:
  build:
    docker:
     - image: openiamdocker/circleci-docker-compose-java
    resource_class: large
    enviornment:
      TZ: "/usr/share/zoneinfo/Etc/UTC"
      DEBIAN_FRONTEND: "noninteractive"
      TERM: "dumb"
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build 2.1 images
          command: |
             . .ci/setup.sh
      - run:
          name: Start Containers
          command: |
             . 2.1/start.sh
      - run:
          name: Verify
          command: |
             . .ci/verify.sh
             
  build_v_3_2:
    docker:
     - image: openiamdocker/circleci-docker-compose-java
    resource_class: large
    enviornment:
      TZ: "/usr/share/zoneinfo/Etc/UTC"
      DEBIAN_FRONTEND: "noninteractive"
      TERM: "dumb"
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build 2.1 images
          command: |
             . .ci/setup.sh
      - run:
          name: Start Containers
          command: |
             . 3.2/setup.sh
             . 3.2/startup.sh
      - run:
          name: Verify
          command: |
             . .ci/verify.sh


workflows:
  version: 2
  build_local:
    jobs:
      - build
      - build_v_3_2