---
version: 2

jobs:
  build:
    docker:
    - image: docker:17.05.0-ce-git
    enviornment:
      TZ: "/usr/share/zoneinfo/Etc/UTC"
      OPENIAM_VERSION_NUMBER: "4.0.0"
      DEBIAN_FRONTEND: "noninteractive"
      OPENIAM_HOME: /opt/openiam/webapps
      OPENIAM_CONF_PATH: /data/openiam
      BUILD_ENVIRONMENT: dev
      MYSQL_ROOT_PASSWORD: mysqlrootpwd
      REDIS_PASSWORD: redispasswd
      TERM: dumb
      DOCKER_COMPOSE_VERSION: "1.14.0"
    steps:
      - run:
          name: Install Curl, Bash and Git
          command: |
            apk --update add curl bash git wget curl py-pip=9.0.1  s-r1
            pip install docker-compose=="1.14.0"
            rm -f /var/cache/apk/*
      - checkout
      - setup_remote_docker
      - run:
          name: Build Images
          command: |
             /bin/sh conf/setup.sh
             /bin/sh conf/package.sh
      - run:
          name: Run back-end
          command: |
             /bin/sh conf/run.sh back-end