---
version: 2

jobs:
  build:
    docker:
     - image: openiamdocker/circleci-docker-compose-java
    resource_class: large
    enviornment:
      TZ: "/usr/share/zoneinfo/Etc/UTC"
      DEBIAN_FRONTEND: "noninteractive"
      TERM: "dumb"
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build 3.0 images
          command: |
             /bin/sh .ci/setup.sh
             docker swarm init
      - run:
          name: Start Containers
          command: |
             ./setup.sh && export DOCKER_COMPOSE_VERSION=3.0 && ./startup.sh
      - run:
          name: Verify
          command: |
             echo "Sleeping for 400s, so that the UI can come up..."
             sleep 400
             /bin/sh .ci/verify.sh
             
  build_v_3_2:
    docker:
     - image: openiamdocker/circleci-docker-compose-java
    resource_class: large
    enviornment:
      TZ: "/usr/share/zoneinfo/Etc/UTC"
      DEBIAN_FRONTEND: "noninteractive"
      TERM: "dumb"
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build 3.2 images
          command: |
             /bin/sh .ci/setup.sh
             docker swarm init
      - run:
          name: Start Containers
          command: |
             ./setup.sh && export DOCKER_COMPOSE_VERSION=3.2 && ./startup.sh
      - run:
          name: Verify
          command: |
             echo "Sleeping for 400s, so that the UI can come up..."
             sleep 400
             /bin/sh .ci/verify.sh


workflows:
  version: 2
  build_local:
    jobs:
      - build
      - build_v_3_2