---
version: 2

jobs:
  build:
    machine: true
    enviornment:
      TZ: "/usr/share/zoneinfo/Etc/UTC"
      DEBIAN_FRONTEND: "noninteractive"
      TERM: "dumb"
    steps:
      - checkout
      - run:
          name: Build 2.1 images
          enviornment:
            BUILD_ENVIRONMENT: "dev"
            MARIADB_BASE_IMAGE_TYPE: "alpine"
          command: |
             . ci/setup.sh
             . 2.1/mysql/back-end/ci/build.sh
  build_one_tier_v2_1_qa:
    machine: true
    enviornment:
      TZ: "/usr/share/zoneinfo/Etc/UTC"
      DEBIAN_FRONTEND: "noninteractive"
      TERM: "dumb"
      BUILD_ENVIRONMENT: "qa"
      MARIADB_BASE_IMAGE_TYPE: "alpine"
    steps:
      - checkout
      - run:
          name: Build 2.1 images
          command: |
             . ci/setup.sh
             . 2.1/mysql/back-end/ci/build.sh
  build_one_tier_v3_2_dev:
    machine: true
    enviornment:
      TZ: "/usr/share/zoneinfo/Etc/UTC"
      DEBIAN_FRONTEND: "noninteractive"
      TERM: "dumb"
      BUILD_ENVIRONMENT: "qa"
    steps:
      - checkout
      - run:
          name: Build 3.2 images
          command: |
             /bin/sh ci/setup.sh
             docker swarm init; sleep 10;
             export BUILD_ENVIRONMENT=qa; export MARIADB_BASE_IMAGE_TYPE=alpine; cd 3.2/ci; /bin/sh build.sh
  build_one_tier_v3_2_qa:
    machine: true
    enviornment:
      TZ: "/usr/share/zoneinfo/Etc/UTC"
      DEBIAN_FRONTEND: "noninteractive"
      TERM: "dumb"
      BUILD_ENVIRONMENT: "qa"
    steps:
      - checkout
      - run:
          name: Build 3.2 images
          command: |
             /bin/sh ci/setup.sh
             docker swarm init; sleep 10;
             export BUILD_ENVIRONMENT=qa; cd 3.2/ci; /bin/sh build.sh
             
             
workflows:
  version: 2
  build_local:
    jobs:
      - build
      - build_one_tier_v2_1_qa
      - build_one_tier_v3_2_dev
      - build_one_tier_v3_2_qa