---
version: 2

jobs:
  build:
    machine: true
    enviornment:
      TZ: "/usr/share/zoneinfo/Etc/UTC"
      OPENIAM_VERSION_NUMBER: "4.0.0"
      DEBIAN_FRONTEND: "noninteractive"
      OPENIAM_HOME: /opt/openiam/webapps
      OPENIAM_CONF_PATH: /data/openiam
      BUILD_ENVIRONMENT: dev
      MYSQL_ROOT_PASSWORD: mysqlrootpwd
      REDIS_PASSWORD: redispasswd
      TERM: dumb
    steps:
      - checkout
      - run:
          name: Build Images
          command: |
             /bin/sh conf/setup.sh
             /bin/sh conf/package.sh
      - run:
          name: Run back-end
          command: |
             /bin/sh conf/run.sh back-end