version: '3.2'
services:
  mariadb:
    image: "openiamdocker/mariadb:${MARIADB_BASE_IMAGE_TYPE}-${OPENIAM_VERSION_NUMBER}-${BUILD_ENVIRONMENT}"
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      OPENIAM_LOG_LEVEL: trace
    volumes:
    - mysql:/var/lib/mysql
    - db:/opt/openiam/webapps/db
    deploy:
      placement:
        constraints:
        - node.role == ${NODE_ROLE:-worker}
      mode: replicated
      replicas: 1
      resources:
        limits:
          memory: 1024m
      restart_policy:
        condition: on-failure
      update_config:
        delay: 1s
        parallelism: 2
    networks:
      openiam_private:
        aliases:
          - mariadb
    ports:
      - 3306
    stop_grace_period: 30s
    healthcheck:
      test: "(healthcheck.sh 120 && exit 0) || exit 1"
      interval: 30s
      timeout: 120s
      retries: 5

networks:
  openiam_private:
    external:
      name: openiam_private
volumes:
  mysql:
    external:
      name: openiam-mysql-storage_storage
  db:
    external:
      name: openiam-db-storage_storage