version: '2.1'
services:
  ui:
    environment:
    - "REDIS_PASSWORD=${REDIS_PASSWORD}"
    - "ESB_HOST=${ESB_HOST}"
    - "ESB_PORT=${ESB_PORT}"
    image: "openiamdocker/ui:alpine-${OPENIAM_VERSION_NUMBER}-${BUILD_ENVIRONMENT}"
    ports:
      - "8080:8080"
    links:
    - redis:redis
    depends_on:
    - redis
    mem_limit: 2048M
    healthcheck:
      test: "(curl -s -f http://localhost:8080/openiam-ui-static/js/common/search/organization.search.js > /dev/null && exit 0) || exit 1"
      interval: 30s
      timeout: 120s
      retries: 8