version: '2.1'
services:
  redis:
    volumes:
    - ./redis-data/:/data
    environment:
    - "REDIS_PASSWORD=${REDIS_PASSWORD}"
    image: "openiamdocker/redis:alpine-${OPENIAM_VERSION_NUMBER}-${BUILD_ENVIRONMENT}"
    healthcheck:
      test: "(healthcheck.sh 120 && exit 0) || exit 1"
      interval: 120s
      timeout: 120s
      retries: 2
  mariadb:
    image: "openiamdocker/mariadb:${MARIADB_BASE_IMAGE_TYPE}-${OPENIAM_VERSION_NUMBER}-${BUILD_ENVIRONMENT}"
    environment:
    - "MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}"
    volumes:
    - ./mysql/:/var/lib/mysql
    - ./db/:/opt/openiam/webapps/db
    healthcheck:
      test: "(healthcheck.sh 120 && exit 0) || exit 1"
      interval: 120s
      timeout: 120s
      retries: 2
  elasticsearch:
    image: "openiamdocker/elasticsearch:alpine-${OPENIAM_VERSION_NUMBER}-${BUILD_ENVIRONMENT}"
#    volumes:
#    - ./elasticsearch/data/:/usr/share/elasticsearch/data
    healthcheck:
      test: "(healthcheck.sh 120 && exit 0) || exit 1"
      interval: 120s
      timeout: 120s
      retries: 2
  rabbitmq:
    image: "openiamdocker/rabbitmq:alpine-${OPENIAM_VERSION_NUMBER}-${BUILD_ENVIRONMENT}"
    healthcheck:
      test: "(healthcheck.sh 120 && exit 0) || exit 1"
      interval: 120s
      timeout: 120s
      retries: 2