version: '2.1'
services:
  tomcat:
    environment:
    - "SPRING_REDIS_PASSWORD=${REDIS_PASSWORD}"
    - OPENIAM_ESB_HOST=esb
    - OPENIAM_ESB_PORT=9080
    image: "openiamdocker/ui:${BUILD_ENVIRONMENT}"
    ports:
      - "8080:8080"
    links:
    - redis:redis
    - esb:esb
    depends_on:
    - redis
    - esb
    mem_limit: 4096M
  redis:
    environment:
    - "REDIS_PASSWORD=${REDIS_PASSWORD}"
    image: "openiamdocker/redis:${BUILD_ENVIRONMENT}"
    ports:
    - "6379:6379"
  esb:
    image: "openiamdocker/esb:${BUILD_ENVIRONMENT}"
    mem_limit: 2048M
    ports:
    - "9080:9080"
    links:
    - mariadb:mariadb
    - elasticsearch:elasticsearch
    - rabbitmq:rabbitmq
    depends_on:
    - mariadb
    - elasticsearch
    - rabbitmq
    - idm
    volumes:
    - ./jks/:/data/openiam/conf/jks
  idm:
    image: "openiamdocker/idm:${BUILD_ENVIRONMENT}"
    links:
    - mariadb:mariadb
    - rabbitmq:rabbitmq
    - elasticsearch:elasticsearch
    mem_limit: 2048M
    depends_on:
    - mariadb
    - elasticsearch
    - rabbitmq
  mariadb:
    image: "openiamdocker/mariadb:${BUILD_ENVIRONMENT}"
    environment:
    - "MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}"
    volumes:
    - ./mysql/:/var/lib/mysql
    - ./db/:/opt/openiam/webapps/db
  elasticsearch:
    image: "openiamdocker/elasticsearch:${BUILD_ENVIRONMENT}"
    volumes:
    - ./elasticsearch/data/:/usr/share/elasticsearch/data
  rabbitmq:
    ports:
    - "5671:5671"
    - "5672:5672"
    image: "openiamdocker/rabbitmq:${BUILD_ENVIRONMENT}"
  groovy_manager:
    image: "openiamdocker/groovy-manager:${BUILD_ENVIRONMENT}"