version: '3.2'
services:
  idm:
    image: "openiamdocker/ldap-connector-rabbitmq:${OPENIAM_VERSION_NUMBER}-${BUILD_ENVIRONMENT}"
    environment:
      OPENIAM_JAVA_HEAP_SIZE: 256M
      OPENIAM_LOG_LEVEL: trace
    networks:
    - openiam
    deploy:
      placement:
        constraints:
        - node.role == ${NODE_ROLE:-worker}
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
      update_config:
        delay: 1s
        parallelism: 2
    stop_grace_period: 10s
    healthcheck:
      test: "(healthcheck.sh 120 && exit 0) || exit 1"
      interval: 60s
      timeout: 120s
      retries: 6

networks:
  openiam:
    external:
      name: openiam