version: '2.1'
services:
  esb:
    environment:
    - "JDBC_HOST=${OPENIAM_JDBC_HOST}"
    - "JDBC_PORT=${OPENIAM_JDBC_PORT}"
    - "JDBC_SCHEMA_NAME=${OPENIAM_JDBC_SCHEMA_NAME}"
    - "JDBC_USERNAME=${OPENIAM_JDBC_USERNAME}"
    - "JDBC_PASSWORD=${OPENIAM_JDBC_PASSWORD}"
    - "JDBC_ACTIVITI_USERNAME=${OPENIAM_ACTIVITI_JDBC_USERNAME}"
    - "JDBC_ACTIVITI_PASSWORD=${OPENIAM_ACTIVITI_JDBC_PASSWORD}"
    - "OPENIAM_PROP_user_timezone=${OPENIAM_ORACLE_TIMEZONE}"
    - OPENIAM_JAVA_HEAP_SIZE=1024M
    image: "openiamdocker/esb:${BUILD_ENVIRONMENT}"
    ports:
    - "9080:9080"
    links:
    - elasticsearch:elasticsearch
    - rabbitmq:rabbitmq
    - redis:redis
    depends_on:
    - elasticsearch
    - rabbitmq
    - redis
    volumes:
    - ./jks/:/data/openiam/conf/jks
    healthcheck:
      test: "(healthcheck.sh 120 && exit 0) || exit 1"
      interval: 120s
      timeout: 120s
      retries: 2
  redis:
    volumes:
    - ./redis-data/:/data
    environment:
    - "REDIS_PASSWORD=${REDIS_PASSWORD}"
    image: "openiamdocker/redis:${BUILD_ENVIRONMENT}"
    healthcheck:
      test: "(healthcheck.sh 120 && exit 0) || exit 1"
      interval: 120s
      timeout: 120s
      retries: 2
  idm:
    image: "openiamdocker/idm:${BUILD_ENVIRONMENT}"
    links:
    - rabbitmq:rabbitmq
    environment:
    - OPENIAM_JAVA_HEAP_SIZE=512M
    depends_on:
    - rabbitmq
    healthcheck:
      test: "(healthcheck.sh 120 && exit 0) || exit 1"
      interval: 120s
      timeout: 120s
      retries: 2
  elasticsearch:
    image: "openiamdocker/elasticsearch:${BUILD_ENVIRONMENT}"
    volumes:
    - ./elasticsearch/data/:/usr/share/elasticsearch/data
    healthcheck:
      test: "(healthcheck.sh 120 && exit 0) || exit 1"
      interval: 120s
      timeout: 120s
      retries: 2
  rabbitmq:
    image: "openiamdocker/rabbitmq:${BUILD_ENVIRONMENT}"
    healthcheck:
      test: "(healthcheck.sh 120 && exit 0) || exit 1"
      interval: 120s
      timeout: 120s
      retries: 2
  groovy_manager:
    image: "openiamdocker/groovy-manager:${BUILD_ENVIRONMENT}"
    links:
    - rabbitmq:rabbitmq
    environment:
    - OPENIAM_JAVA_HEAP_SIZE=512M
    depends_on:
    - rabbitmq
    healthcheck:
      test: "(healthcheck.sh 120 && exit 0) || exit 1"
      interval: 120s
      timeout: 120s
      retries: 2
  workflow:
    environment:
    - "JDBC_HOST=${OPENIAM_JDBC_HOST}"
    - "JDBC_PORT=${OPENIAM_JDBC_PORT}"
    - "JDBC_SCHEMA_NAME=${OPENIAM_JDBC_SCHEMA_NAME}"
    - "JDBC_USERNAME=${OPENIAM_JDBC_USERNAME}"
    - "JDBC_PASSWORD=${OPENIAM_JDBC_PASSWORD}"
    - "JDBC_ACTIVITI_USERNAME=${OPENIAM_ACTIVITI_JDBC_USERNAME}"
    - "JDBC_ACTIVITI_PASSWORD=${OPENIAM_ACTIVITI_JDBC_PASSWORD}"
    - "OPENIAM_PROP_user_timezone=${OPENIAM_ORACLE_TIMEZONE}"
    - OPENIAM_JAVA_HEAP_SIZE=1024M
    image: "openiamdocker/workflow:${BUILD_ENVIRONMENT}"
    links:
    - rabbitmq:rabbitmq
    depends_on:
    - rabbitmq
    volumes:
    - ./activiti/:/data/openiam/conf/activiti
    healthcheck:
      test: "(healthcheck.sh 120 && exit 0) || exit 1"
      interval: 120s
      timeout: 120s
      retries: 2