# This is a docker compose file for traefik router adn load balancer.
# To start, use the following command:
# ```
# docker stack deploy --compose-file docker-compose.yml traefik
# ```
# You can check the LB health using:
# ```
# curl -vvv -H "Host: openiam.com" http://localhost:8080/health
# ```
# To use the UI:
# ```
# http://localhost:8080
# ```
---
version: "3.2"
services:
  openiam:
    command: --docker --docker.swarmmode --docker.domain=openiam.com --docker.watch --web --logLevel=DEBUG
    deploy:
      mode: global
      # We might want to run them on ALL nodes. For now we run them on the managers.
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          memory: 32M
      restart_policy:
        condition: on-failure
      update_config:
        delay: 1s
        parallelism: 2
    image: docker.io/traefik:v1.3.2
    networks:
      - openiam
    ports:
      - "80:80"
      - "8080:8080"
      - "9080:9080"
    stop_grace_period: 30s
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  openiam:
    external:
      name: openiam
