version: '2.1'
services:
  esb:
    image: "openiamdocker/esb:${BUILD_ENVIRONMENT}"
    mem_limit: 2048M
    ports:
    - "9080:9080"
    links:
    - mariadb:mariadb
    - elasticsearch:elasticsearch
    - rabbitmq:rabbitmq
    depends_on:
    - mariadb
    - elasticsearch
    - rabbitmq
    - idm
    volumes:
    - ./jks/:/data/openiam/conf/jks
    healthcheck:
      test: "(healthcheck.sh 120 && exit 0) || exit 1"
      interval: 120s
      timeout: 120s
      retries: 2
  idm:
    image: "openiamdocker/idm:${BUILD_ENVIRONMENT}"
    links:
    - rabbitmq:rabbitmq
    - elasticsearch:elasticsearch
    mem_limit: 1024M
    depends_on:
    - elasticsearch
    - rabbitmq
    healthcheck:
      test: "(healthcheck.sh 120 && exit 0) || exit 1"
      interval: 120s
      timeout: 120s
      retries: 2
  mariadb:
    image: "openiamdocker/mariadb:${BUILD_ENVIRONMENT}"
    environment:
    - "MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}"
    volumes:
    - ./mysql/:/var/lib/mysql
    - ./db/:/opt/openiam/webapps/db
    healthcheck:
      test: "(healthcheck.sh 120 && exit 0) || exit 1"
      interval: 120s
      timeout: 120s
      retries: 2
  elasticsearch:
    image: "openiamdocker/elasticsearch:${BUILD_ENVIRONMENT}"
    volumes:
    - ./elasticsearch/data/:/usr/share/elasticsearch/data
    healthcheck:
      test: "(healthcheck.sh 120 && exit 0) || exit 1"
      interval: 120s
      timeout: 120s
      retries: 2
  rabbitmq:
    image: "openiamdocker/rabbitmq:${BUILD_ENVIRONMENT}"
    healthcheck:
      test: "(healthcheck.sh 120 && exit 0) || exit 1"
      interval: 120s
      timeout: 120s
      retries: 2
  groovy_manager:
    image: "openiamdocker/groovy-manager:${BUILD_ENVIRONMENT}"
    links:
    - rabbitmq:rabbitmq
    mem_limit: 1024M
    depends_on:
    - rabbitmq
    healthcheck:
      test: "(healthcheck.sh 120 && exit 0) || exit 1"
      interval: 120s
      timeout: 120s
      retries: 2
  workflow:
    image: openiamdocker/workflow:dev
    links:
    - mariadb:mariadb
    - rabbitmq:rabbitmq
    mem_limit: 1024M
    depends_on:
    - mariadb
    - rabbitmq
    volumes:
    - ./activiti/:/data/openiam/conf/activiti
    healthcheck:
      test: "(healthcheck.sh 120 && exit 0) || exit 1"
      interval: 120s
      timeout: 120s
      retries: 2