version: '2.1'
services:
  tomcat:
    environment:
    - "SPRING_REDIS_PASSWORD=${REDIS_PASSWORD}"
    - "OPENIAM_ESB_PORT=${ESB_PORT}"
    - "OPENIAM_ESB_HOST=${ESB_HOST}"
    image: "openiamdocker/ui:${BUILD_ENVIRONMENT}"
    ports:
      - "8080:8080"
    links:
    - redis:redis
    depends_on:
    - redis
    mem_limit: 4096M
  redis:
    environment:
    - "REDIS_PASSWORD=${REDIS_PASSWORD}"
    image: "openiamdocker/redis:${BUILD_ENVIRONMENT}"
    ports:
    - "6379:6379"