version: '3.0'
services:
  esb:
    image: "openiamdocker/esb:alpine-${OPENIAM_VERSION_NUMBER}-${BUILD_ENVIRONMENT}"
    environment:
      REDIS_PASSWORD: "${REDIS_PASSWORD}"
      OPENIAM_JAVA_HEAP_SIZE: 1024M
      OPENIAM_LOG_LEVEL: trace
      DB_TYPE: "${DB_TYPE}"
######## Oracle #########
#      JDBC_HOST: "${JDBC_HOST}"
#      JDBC_PORT: "${JDBC_PORT}"
#      JDBC_SID: "${JDBC_SID}"
#      JDBC_SERVICE_NAME: "${JDBC_SERVICE_NAME}"
#      JDBC_SCHEMA_NAME: "${JDBC_SCHEMA_NAME}"
#      JDBC_USERNAME: "${JDBC_USERNAME}"
#      JDBC_PASSWORD: "${JDBC_PASSWORD}"
#      JDBC_ACTIVITI_USERNAME: "${JDBC_ACTIVITI_USERNAME}"
#      JDBC_ACTIVITI_PASSWORD: "${JDBC_ACTIVITI_PASSWORD}"
#      OPENIAM_PROP_user_timezone: "${ORACLE_USER_TIMEZONE}"
#      OPENIAM_HIBERNATE_DIALECT: "org.hibernate.dialect.Oracle10gDialect"
######## End Oracle #########

######## MSSQL #########
#      JDBC_HOST: "${JDBC_HOST}"
#      JDBC_PORT: "${JDBC_PORT}"
#      JDBC_SCHEMA_NAME: "${JDBC_SCHEMA_NAME}"
#      JDBC_USERNAME: "${JDBC_USERNAME}"
#      JDBC_PASSWORD: "${JDBC_PASSWORD}"
#      JDBC_ACTIVITI_USERNAME: "${JDBC_ACTIVITI_USERNAME}"
#      JDBC_ACTIVITI_PASSWORD: "${JDBC_ACTIVITI_PASSWORD}"
#      JDBC_DATABASE_NAME: "${JDBC_DATABASE_NAME}"
#      JDBC_ACTIVITI_DATABASE_NAME: "${JDBC_ACTIVITI_DATABASE_NAME}"
#      OPENIAM_HIBERNATE_DIALECT: "org.hibernate.dialect.SQLServer2012Dialect"
######## End MSSQL #########
    volumes:
    - jks:/data/openiam/conf/jks
    ports:
    #- "9080:9080"
    - "9080"
    networks:
      openiam_private:
        aliases:
          - esb
    deploy:
      labels:
      - "traefik.port=9080"
      - "traefik.docker.network=openiam_private"
      - "traefik.backend=esb"
      #- "traefik.frontend.rule=Host:esb.openiam.com"
      #- "traefik.frontend.rule=Host:esb.openiam.com,Path:/openiam-esb"
      - "traefik.frontend.rule=PathPrefix:/openiam-esb"
      placement:
        constraints:
        - node.role == ${NODE_ROLE:-worker}
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
      update_config:
        delay: 1s
        parallelism: 2
    stop_grace_period: 10s
    healthcheck:
      test: "(healthcheck.sh 120 && exit 0) || exit 1"
      interval: 60s
      timeout: 120s
      retries: 6
  idm:
    image: "openiamdocker/idm:alpine-${OPENIAM_VERSION_NUMBER}-${BUILD_ENVIRONMENT}"
    environment:
      OPENIAM_JAVA_HEAP_SIZE: 512M
      OPENIAM_LOG_LEVEL: trace
    networks:
    - openiam_private
    deploy:
      placement:
        constraints:
        - node.role == ${NODE_ROLE:-worker}
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
      update_config:
        delay: 1s
        parallelism: 2
    stop_grace_period: 10s
    healthcheck:
      test: "(healthcheck.sh 120 && exit 0) || exit 1"
      interval: 60s
      timeout: 120s
      retries: 6
  synchronization:
    image: "openiamdocker/synchronization:alpine-${OPENIAM_VERSION_NUMBER}-${BUILD_ENVIRONMENT}"
    environment:
      OPENIAM_JAVA_HEAP_SIZE: 512M
      OPENIAM_LOG_LEVEL: trace
    networks:
    - openiam_private
    deploy:
      placement:
        constraints:
        - node.role == ${NODE_ROLE:-worker}
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
      update_config:
        delay: 1s
        parallelism: 2
    stop_grace_period: 10s
    healthcheck:
      test: "(healthcheck.sh 120 && exit 0) || exit 1"
      interval: 60s
      timeout: 120s
      retries: 6

  groovy_manager:
    image: "openiamdocker/groovy-manager:alpine-${OPENIAM_VERSION_NUMBER}-${BUILD_ENVIRONMENT}"
    environment:
      OPENIAM_JAVA_HEAP_SIZE: 256M
      OPENIAM_LOG_LEVEL: trace
    networks:
    - openiam_private
    deploy:
      placement:
        constraints:
        - node.role == ${NODE_ROLE:-worker}
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
      update_config:
        delay: 1s
        parallelism: 2
    stop_grace_period: 10s
    healthcheck:
      test: "(healthcheck.sh 120 && exit 0) || exit 1"
      interval: 60s
      timeout: 120s
      retries: 6
  workflow:
    image: "openiamdocker/workflow:alpine-${OPENIAM_VERSION_NUMBER}-${BUILD_ENVIRONMENT}"
    environment:
      OPENIAM_JAVA_HEAP_SIZE: 1024M
      OPENIAM_LOG_LEVEL: trace
      DB_TYPE: "${DB_TYPE}"
######## Oracle #########
#      JDBC_HOST: "${JDBC_HOST}"
#      JDBC_PORT: "${JDBC_PORT}"
#      JDBC_SID: "${JDBC_SID}"
#      JDBC_SERVICE_NAME: "${JDBC_SERVICE_NAME}"
#      JDBC_SCHEMA_NAME: "${JDBC_SCHEMA_NAME}"
#      JDBC_USERNAME: "${JDBC_USERNAME}"
#      JDBC_PASSWORD: "${JDBC_PASSWORD}"
#      JDBC_ACTIVITI_USERNAME: "${JDBC_ACTIVITI_USERNAME}"
#      JDBC_ACTIVITI_PASSWORD: "${JDBC_ACTIVITI_PASSWORD}"
#      OPENIAM_PROP_user_timezone: "${ORACLE_USER_TIMEZONE}"
#      OPENIAM_HIBERNATE_DIALECT: "org.hibernate.dialect.Oracle10gDialect"
######## End Oracle #########

######## MSSQL #########
#      JDBC_HOST: "${JDBC_HOST}"
#      JDBC_PORT: "${JDBC_PORT}"
#      JDBC_SCHEMA_NAME: "${JDBC_SCHEMA_NAME}"
#      JDBC_USERNAME: "${JDBC_USERNAME}"
#      JDBC_PASSWORD: "${JDBC_PASSWORD}"
#      JDBC_ACTIVITI_USERNAME: "${JDBC_ACTIVITI_USERNAME}"
#      JDBC_ACTIVITI_PASSWORD: "${JDBC_ACTIVITI_PASSWORD}"
#      JDBC_DATABASE_NAME: "${JDBC_DATABASE_NAME}"
#      JDBC_ACTIVITI_DATABASE_NAME: "${JDBC_ACTIVITI_DATABASE_NAME}"
#      OPENIAM_HIBERNATE_DIALECT: "org.hibernate.dialect.SQLServer2012Dialect"
######## End MSSQL #########
    volumes:
    - activiti:/data/openiam/conf/activiti
    networks:
    - openiam_private
    deploy:
      placement:
        constraints:
        - node.role == ${NODE_ROLE:-worker}
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
      update_config:
        delay: 1s
        parallelism: 2
    stop_grace_period: 10s
    healthcheck:
      test: "(healthcheck.sh 120 && exit 0) || exit 1"
      interval: 60s
      timeout: 120s
      retries: 6

networks:
  openiam_private:
    external:
      name: openiam_private
volumes:
  activiti:
    external:
      name: openiam-activiti-storage_storage
  jks:
    external:
      name: openiam-jks-storage_storage
